platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'WattsAppKauaiNewest' do
  # Pods for WattsAppKauaiNewest
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  target 'WattsAppKauaiNewestTests' do
    inherit! :search_paths
  end
end